services:
  ghost:
    image: ghost:5
    restart: unless-stopped
    depends_on: [db]
    env_file: ./.env
    environment:
      url: ${SITE_URL}
      database__client: mysql
      database__connection__host: db
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ${MYSQL_DATABASE}
    volumes:
      - ghost_content:/var/lib/ghost/content
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${ROUTER_NAME}.rule=Host(`${SITE_HOST}`)"
      - "traefik.http.routers.${ROUTER_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${ROUTER_NAME}.tls.certresolver=le"

  db:
    image: mysql:8.4
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ghost_mysql:/var/lib/mysql

volumes:
  ghost_content:
  ghost_mysql:
